[package]
name = "jinglebells"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
cpal = "0.16.0"
rodio = "0.21.1"
hound = "3.5"
rand = "0.8"
lame = { version = "0.1.3", optional = true }

[features]
default = []
mp3 = ["lame"]
